    export const cuisineList = [
    "Cozidos",
    "Salteados",
    "Fritos",
    "Assados",
    "Grelhados",
    "Estufados/Guisados",
    "Vegano",
    "Escalfados",
    "Saudável",
    "Mariscos",
    "Pizza",
    "Pequeno-almoco",
    "Chinesa",
    "Indiana",
    "Mexicana",
    "Asiática",
    "Italiana",
    "Tailandesa",
    "Coreana",
    "Padaria",
    "Bubble Tea",
    "Sopa",
    "Gelado",
  ];